apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: helloworld
  newName: us-west1-docker.pkg.dev/boingo-helloworld/hello-docker-repo/helloworld
  newTag: newtag
replicas:
- name: helloworld
  count: 2

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
